version: '2.3'

services:
  face_recognition:
    image: py_face_recognition
    container_name: py_face_recognition
    working_dir: /py_face_recognition
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/py_face_recognition
