# Generated by Django 3.1.5 on 2021-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='face_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceimage',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
