# Generated by Django 3.1.5 on 2021-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210123_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='face_hash',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='faceimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
