# Generated by Django 3.1.5 on 2021-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210123_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='face_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
