# Generated by Django 3.1.5 on 2021-01-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20210123_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='face_hash_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
