# Generated by Django 3.1.5 on 2021-01-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_faceimage_face_hash_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceimage',
            name='face_hash_txt',
        ),
    ]
